name: unit-tests

on: push

jobs:
    unit_tests:
        runs-on: ubuntu-latest

        steps:
            - name: Check out repository code
              uses: actions/checkout@v3
            - name: use node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18.x'
            - name: npi install
              run: npm ci
            - name: tests
              run: npm test
